# Generated by Django 5.0.6 on 2024-06-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_sequential_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sequential_number',
        ),
    ]
