# Generated by Django 5.0.6 on 2024-06-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cashreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='product_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='recipient_email',
            field=models.EmailField(default='h', max_length=254),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='recipient_name',
            field=models.CharField(default='hi', max_length=100),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
