# Generated by Django 5.0.6 on 2024-06-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_cashreceipt_product_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='product_details',
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='webapp.cashreceipt')),
            ],
        ),
    ]
