# Generated by Django 4.2.7 on 2024-06-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_cashreceipt_product_details_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='receipt_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='receipt_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='receipt_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
