# Generated by Django 4.2.7 on 2024-06-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_cashreceipt_receipt_item_cashreceipt_receipt_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='receipt_item',
            field=models.EmailField(default='name of product', max_length=254),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='receipt_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='receipt_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
