# Generated by Django 4.2.7 on 2024-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_cashreceipt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='receipt_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
